name: automl_object_detection_example
description: Demonstrates how to use the automl_object_detection plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  automl_object_detection:
    path: ../
  camera2:
    git:
      url: https://github.com/s0nerik/camera2.git
      ref: 72d031bf4a21e8c1b5c9a8059e60fc937fa68dd9
  permission_handler: ^5.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
